[package]
name = "oxup"
version = "2.0.1"
edition = "2021"

[profile.release]
strip = true
lto = true
opt-level = "z"

[dependencies]
flate2 = { version = "1.0.24", features = ["zlib-ng"], default-features = false }
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4.38"
tokio = { version = "0.2", features = ["macros"] }
zip = { version = "0.6.2", features = ["deflate"], default-features = false }
