on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            name: oxup-windows
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
            name: oxup-linux
          - target: x86_64-apple-darwin
            archive: zip
            name: oxup-darwin
    steps:
      - uses: actions/checkout@master
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ""
          key: ""
          env-vars: ""
          workspaces: ""
          cache-on-failure: ""
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          ARCHIVE_NAME: ${{ matrix.name }}