on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            name: oxup.exe
          - target: x86_64-unknown-linux-musl
            name: oxup
          - target: x86_64-apple-darwin
            name: oxup-darwin
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: cp target/release/$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].targets[] | select( .kind | map(. == "bin") | any ) | .name') $(echo ${{ matrix.name }})
      - uses: ncipollo/release-action@v1
        with:
          name: Release
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          artifacts: ${{ matrix.name }}